// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vkzujcgkvnifnodwygoj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZrenVqY2drdm5pZm5vZHd5Z29qIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg5MjgwNzIsImV4cCI6MjA2NDUwNDA3Mn0.kks71bvNl_TR_71xY66Ux-QwtC2b9-lCE24TXG4hoMA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);